### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by cemnura** [newrelic/micrometer-registry-newrelic#127]
Hello,

I have been trying to use new relic microregistry with quarkus. I have the following new relic microregistry depedency.

```
        <dependency>
            <groupId>com.newrelic.telemetry</groupId>
            <artifactId>micrometer-registry-new-relic</artifactId>
            <version>0.7.0</version>
        </dependency>
```

I successfully created a client such as the folllowing

```
@Produces
    @Singleton
    public NewRelicRegistry registry() throws UnknownHostException {

        NewRelicRegistryConfig newRelicRegistryConfig = new NewRelicRegistryConfig() {
            @Override
            public String get(String key) {
                return null;
            }

            @Override
            public String apiKey() {
                return "NRII-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"; // Insights Insert apiKey
            }

            @Override
            public Duration step() {
                return Duration.ofSeconds(10);
            }

            @Override
            public String uri() {
                return "https://metric-api.eu.newrelic.com"; 
            }

            @Override
            public String serviceName() {
                return "Test Service";
            }
        };

        NewRelicRegistry newRelicRegistry =
                NewRelicRegistry.builder(newRelicRegistryConfig)
                        .commonAttributes(
                                new Attributes()
                                        .put("host", InetAddress.getLocalHost().getHostName()))
                        .build();
        newRelicRegistry.start(new NamedThreadFactory("newrelic.micrometer.registry"));
        return newRelicRegistry;
    }

```

However, I am recieving 404 errors.

Thinking that I got everthing correct I thought I should test downgrading the version to

```
        <dependency>
            <groupId>com.newrelic.telemetry</groupId>
            <artifactId>micrometer-registry-new-relic</artifactId>
            <version>0.6.0</version>
        </dependency>
```

Surprisingly, this fixed the problem.

Seems like the 404 error is `0.7.0` version specific.

**Comment by kford-newrelic** [comment]
@cemnura are you able to try this scenario with the latest version - `0.9.0` - does the same error still result?

**Comment by snekse** [comment]
I am also getting a 404 error when trying to use this library. 

I am using the URI `https://insights-collector.newrelic.com` 

Also using:
`com.newrelic.agent.java:newrelic-api:7.9.0`
`com.newrelic.telemetry:micrometer-registry-new-relic:0.10.0`
`io.micrometer:micrometer-core:1.9.3`

This is the StackTrace 
```
DEBUG com.newrelic.telemetry.metrics.MetricBatchSender - Sending a metric batch (number of metrics: 1) to the New Relic metric ingest endpoint)
DEBUG com.newrelic.telemetry.metrics.json.MetricBatchMarshaller - Generating json for metric batch.
DEBUG com.newrelic.telemetry.transport.BatchDataSender - Response from New Relic ingest API for MetricBatch: code: 404, body: {}
WARN  com.newrelic.telemetry.transport.BatchDataSender - Response from New Relic ingest API. Discarding MetricBatch recommended.: code: 404, body: {}
ERROR com.newrelic.telemetry.TelemetryClient - [MetricBatch] - Received a fatal exception from the New Relic API. Aborting batch send.
com.newrelic.telemetry.exceptions.DiscardBatchException: The New Relic API failed to process this request and it should not be retried.
	at com.newrelic.telemetry.transport.BatchDataSender.sendPayload(BatchDataSender.java:178)
	at com.newrelic.telemetry.transport.BatchDataSender.send(BatchDataSender.java:114)
	at com.newrelic.telemetry.metrics.MetricBatchSender.sendBatch(MetricBatchSender.java:63)
	at com.newrelic.telemetry.TelemetryClient.lambda$sendBatch$0(TelemetryClient.java:144)
	at com.newrelic.telemetry.TelemetryClient.sendWithErrorHandling(TelemetryClient.java:212)
	at com.newrelic.telemetry.TelemetryClient.lambda$scheduleBatchSend$4(TelemetryClient.java:201)
	at com.newrelic.telemetry.LimitingScheduler.lambda$schedule$0(LimitingScheduler.java:52)
```

**Comment by meiao** [comment]
@snekse can you try using the URI `https://metric-api.newrelic.com`.
Or you can even remove the uri method and it will use the default.

**Comment by snekse** [comment]
The metrics-api URI also is giving me a 404

FYI, the insights URI came from these pages

[NR Blog: How to monitor Spring Boot applications](https://newrelic.com/blog/how-to-relic/how-to-monitor-spring-boot-applications-using-micrometer-metrics)

[New Relic Micrometer registry README](https://github.com/newrelic/micrometer-registry-newrelic/blob/main/README.md) (Step 3)

[NR micrometer-registry-newrelic wiki example](https://github.com/newrelic/micrometer-registry-newrelic/wiki/Spring-Config-Example)

**Comment by snekse** [comment]
@meiao Should I be able to POST to these URLs through Postman/Insomnia?  I'm getting a 404 when I try with those tools, which makes me think maybe there's something else going on

**Comment by snekse** [comment]
Sorry to comment spam this issue, but I may have partially resolved this. 

Following the guidance from this issue #128 [comment](https://github.com/newrelic/micrometer-registry-newrelic/issues/128#issuecomment-1095526162), adding `/metric/v1` to the URI gives me a 202 when I submit the request via Postman.

**Comment by meiao** [comment]
That was gonna be my next suggestion, when you mentioned you still got 404.
Probably this is the solution for the original issue.

**Comment by snekse** [comment]
I think addressing Issue 128 would be helpful.

The [README](https://github.com/newrelic/micrometer-registry-newrelic/blob/main/README.md) for this project and the [Wiki example](https://github.com/newrelic/micrometer-registry-newrelic/wiki/Spring-Config-Example) don't really give any obvious guidance for this.  

I think I had grabbed the "insights-collector" URI from the MicroMeter and/or Spring Boot defaults.  

That said, I do also see that if I completely remove setting that property, the telemetry library must be doing some magic and using the proper URI all on it's own. 

Thanks for your time on this.
